version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake test

workflows:
  version: 2
  test:
    jobs:
      - test
